export const ELEMENTS = [
    {
        title: "Dashboard",
        href: "",
        iconClass: "bx bxs-dashboard",
        hasSubMenu: false,
        parentMenuisActive: false,
        submenuIsActive: false,
        submenus: [],
    },
    {
        component: "RealEstateListView",
        title: "Gayrimenkuller",
        href: "/real-estates",
        iconClass: "bx bx-buildings",
        hasSubMenu: false,
        parentMenuisActive: false,
        submenuIsActive: false,
        submenus: [],
    },
    {
        title: "Raporlar",
        href: "",
        iconClass: "bx bxs-report",
        hasSubMenu: false,
        parentMenuisActive: false,
        submenuIsActive: false,
        submenus: [],
    },
    {
        title: "Onay",
        href: "",
        iconClass: "bx bx-badge-check",
        parentMenuisActive: false,
        hasSubMenu: false,
        submenuIsActive: false,
        submenus: [],
    },
    {
        title: "Sistem Tanımları",
        href: "",
        iconClass: "bx bx-edit-alt",
        hasSubMenu: true,
        parentMenuisActive: false,
        submenuIsActive: false,
        submenus: [
            { component: "CategoryView", title: "Kategoriler", href: "/categories", isActive: false },
            { component: "AdvertPlaceView", title: "İlan Yerleri", href: "/advert-places", isActive: false },
            { component: "AttributeView", title: "Özellikler", href: "/attributes", isActive: false },
        ],
    },
    {
        title: "Kullanıcı Yönetimi",
        href: "",
        iconClass: "bx bx-edit-alt",
        hasSubMenu: true,
        parentMenuisActive: false,
        submenuIsActive: false,
        submenus: [
            { component: "StaffView", title: "Alt Kullanıcılar", href: "/staffs", isActive: false },
            { component: "TenantView", title: "Kiracılar", href: "/tenants", isActive: false },
        ],
    },
    {
        title: "Güvenlik",
        href: "",
        iconClass: "bx bxs-key",
        hasSubMenu: true,
        parentMenuisActive: false,
        submenuIsActive: false,
        submenus: [
            { component: "RoleView", title: "Roller", href: "/roles", isActive: false },
        ],
    },
]